# Generated by Django 4.1.3 on 2022-11-15 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pizzariaDev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_Compra', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pizzariaDev.endereco'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=20)),
                ('img', models.CharField(max_length=255)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pizzariaDev.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDeProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Fabricacao', models.DateField(blank=True, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('preco_Atualizado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_Carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pizzariaDev.carrinho')),
                ('id_Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pizzariaDev.produto')),
            ],
        ),
    ]
