# Generated by Django 4.1.3 on 2022-11-15 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_pizzariaDev', '0002_carrinho_categoria_alter_profile_id_endereco_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_Total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_Carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pizzariaDev.carrinho')),
                ('id_Endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pizzariaDev.endereco')),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Venda', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('F', 'Finalizada'), ('C', 'Cancelada'), ('E', 'Em Andamento')], default='E', max_length=4)),
                ('preco_Total_Venda', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pizzariaDev.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('pix', 'PIX'), ('car', 'Cartao'), ('din', 'Dinheiro')], default='pix', max_length=4)),
                ('id_Venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pizzariaDev.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_Entrega', models.CharField(choices=[('F', 'Finalizada'), ('C', 'Cancelada'), ('E', 'Em Andamento'), ('P', 'Parada')], default='E', max_length=4)),
                ('data_Envio', models.DateField(blank=True, null=True)),
                ('data_Chegada', models.DateField(blank=True, null=True)),
                ('id_Venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pizzariaDev.venda')),
            ],
        ),
    ]
