# Generated by Django 4.1.3 on 2022-11-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pizzariaDev', '0003_pedido_venda_pagamento_entrega'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
